language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "pypy"
install:
 - "python setup.py install"
 - "pip install --use-mirrors pep8"
script:
 - "pep8 --ignore=E221,E241 --statistics routr/*.py"
 - "python setup.py test"
